export const categoryTree = [
  {
    name: 'Laptops',
    children: ['Laptops Gaming', 'Ultrabooks', 'Laptops Empresariales'],
  },
  {
    name: 'Smartphones',
    children: ['Android', 'iPhone', 'Gama Media'],
  },
  {
    name: 'Componentes PC',
    children: [
      'Procesadores',
      'Placas de Video',
      'Memorias RAM',
      'Motherboards',
      'Fuentes de Poder',
    ],
  },
  {
    name: 'Monitores',
    children: ['Monitores Gaming', 'Monitores 4K', 'Monitores Ultrawide'],
  },
  {
    name: 'Periféricos',
    children: ['Teclados', 'Mouse', 'Auriculares', 'Webcams'],
  },
  {
    name: 'Almacenamiento',
    children: ['SSD', 'HDD', 'Pendrives', 'Discos Externos'],
  },
  {
    name: 'Tablets',
    children: ['iPad', 'Android Tablets'],
  },
  {
    name: 'Accesorios',
    children: ['Cables', 'Hubs USB', 'Soportes', 'Cooling Pads'],
  },
];

export const brandsData = [
  'ASUS',
  'MSI',
  'Lenovo',
  'Apple',
  'Dell',
  'LG',
  'Samsung',
  'Google',
  'Xiaomi',
  'Motorola',
  'AMD',
  'Intel',
  'NVIDIA',
  'Corsair',
  'Kingston',
  'Logitech',
  'Keychron',
  'Razer',
  'Sony',
  'Jabra',
  'WD',
  'Seagate',
];

export const productsData = [
  {
    name: 'ASUS ROG Strix G16',
    price: 1299.99,
    stock: 8,
    category: 'Laptops Gaming',
    brand: 'ASUS',
  },
  {
    name: 'MSI Raider GE78 HX',
    price: 1899.99,
    stock: 5,
    category: 'Laptops Gaming',
    brand: 'MSI',
  },
  {
    name: 'Lenovo Legion 5 Pro',
    price: 1099.99,
    stock: 10,
    category: 'Laptops Gaming',
    brand: 'Lenovo',
  },
  {
    name: 'MacBook Air M3',
    price: 1499.99,
    stock: 12,
    category: 'Ultrabooks',
    brand: 'Apple',
  },
  {
    name: 'Dell XPS 13 Plus',
    price: 1199.99,
    stock: 7,
    category: 'Ultrabooks',
    brand: 'Dell',
  },
  {
    name: 'LG Gram 17',
    price: 999.99,
    stock: 6,
    category: 'Ultrabooks',
    brand: 'LG',
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    price: 1299.99,
    stock: 15,
    category: 'Android',
    brand: 'Samsung',
  },
  {
    name: 'Google Pixel 8 Pro',
    price: 999.99,
    stock: 9,
    category: 'Android',
    brand: 'Google',
  },
  {
    name: 'iPhone 15 Pro Max',
    price: 1399.99,
    stock: 11,
    category: 'iPhone',
    brand: 'Apple',
  },
  {
    name: 'WD Black SN850X 1TB',
    price: 119.99,
    stock: 22,
    category: 'SSD',
    brand: 'WD',
  },
  {
    name: 'Seagate Barracuda 4TB',
    price: 89.99,
    stock: 15,
    category: 'HDD',
    brand: 'Seagate',
  },
  {
    name: 'Samsung Galaxy Tab S9',
    price: 799.99,
    stock: 10,
    category: 'Android Tablets',
    brand: 'Samsung',
  },
  {
    name: 'iPad Pro M4',
    price: 1099.99,
    stock: 8,
    category: 'iPad',
    brand: 'Apple',
  },
  {
    name: 'Logitech MX Master 3S',
    price: 99.99,
    stock: 25,
    category: 'Mouse',
    brand: 'Logitech',
  },
  {
    name: 'Sony WH-1000XM5',
    price: 349.99,
    stock: 18,
    category: 'Auriculares',
    brand: 'Sony',
  },
  {
    name: 'NVIDIA RTX 4090',
    price: 1999.99,
    stock: 4,
    category: 'Placas de Video',
    brand: 'NVIDIA',
  },
  {
    name: 'Corsair Vengeance 32GB DDR5',
    price: 199.99,
    stock: 30,
    category: 'Memorias RAM',
    brand: 'Corsair',
  },
  {
    name: 'Logitech MX Keys S',
    price: 129.99,
    stock: 20,
    category: 'Teclados',
    brand: 'Logitech',
  },
  {
    name: 'LG UltraGear 27" 144Hz',
    price: 299.99,
    stock: 10,
    category: 'Monitores Gaming',
    brand: 'LG',
  },
  {
    name: 'Keychron K8 Pro',
    price: 129.99,
    stock: 15,
    category: 'Teclados',
    brand: 'Keychron',
  },
  {
    name: 'Razer DeathAdder V3',
    price: 49.99,
    stock: 40,
    category: 'Mouse',
    brand: 'Razer',
  },
  {
    name: 'AMD Ryzen 9 7950X',
    price: 699.99,
    stock: 8,
    category: 'Procesadores',
    brand: 'AMD',
  },
  {
    name: 'Kingston Fury Beast 16GB',
    price: 79.99,
    stock: 50,
    category: 'Memorias RAM',
    brand: 'Kingston',
  },
  {
    name: 'Samsung 990 Pro 2TB NVMe',
    price: 249.99,
    stock: 12,
    category: 'SSD',
    brand: 'Samsung',
  },
  {
    name: 'Jabra Evolve2 85',
    price: 229.99,
    stock: 14,
    category: 'Auriculares',
    brand: 'Jabra',
  },
  {
    name: 'NVIDIA RTX 4070 Ti',
    price: 799.99,
    stock: 6,
    category: 'Placas de Video',
    brand: 'NVIDIA',
  },
];

export const customersData = [
  { name: 'Juan Pérez', email: 'juan.perez@gmail.com', phone: '1123456789' },
  {
    name: 'María García',
    email: 'maria.garcia@gmail.com',
    phone: '1134567890',
  },
  {
    name: 'Carlos López',
    email: 'carlos.lopez@hotmail.com',
    phone: '1145678901',
  },
  {
    name: 'Ana Martínez',
    email: 'ana.martinez@gmail.com',
    phone: '1156789012',
  },
  {
    name: 'Lucas Rodríguez',
    email: 'lucas.rodriguez@gmail.com',
    phone: '1167890123',
  },
  {
    name: 'Valentina Fernández',
    email: 'vale.fernandez@gmail.com',
    phone: '1178901234',
  },
  {
    name: 'Diego González',
    email: 'diego.gonzalez@outlook.com',
    phone: '1189012345',
  },
  {
    name: 'Sofía Torres',
    email: 'sofia.torres@gmail.com',
    phone: '1190123456',
  },
];

export const salesData = [
  {
    customer: 'Juan Pérez',
    status: 'COMPLETED',
    paymentMethod: 'Tarjeta de Crédito',
    notes: 'Pedido completado\nPor: Administrador',
    items: [
      { product: 'MacBook Air M3', quantity: 1 },
      { product: 'Logitech MX Master 3S', quantity: 1 },
    ],
  },
  {
    customer: 'María García',
    status: 'SHIPPED',
    paymentMethod: 'Tarjeta de Débito',
    trackingCode: '7849321056',
    notes: 'Pedido enviado con tracking: 7849321056\nPor: Administrador',
    items: [
      { product: 'iPhone 15 Pro Max', quantity: 1 },
      { product: 'Sony WH-1000XM5', quantity: 1 },
    ],
  },
  {
    customer: 'Carlos López',
    status: 'PREPARING',
    paymentMethod: 'Tarjeta de Crédito',
    notes: 'Pedido en preparación\nPor: Administrador',
    items: [
      { product: 'NVIDIA RTX 4090', quantity: 1 },
      { product: 'Corsair Vengeance 32GB DDR5', quantity: 2 },
    ],
  },
  {
    customer: 'Ana Martínez',
    status: 'PENDING',
    paymentMethod: 'Tarjeta de Débito',
    items: [{ product: 'Samsung Galaxy S24 Ultra', quantity: 1 }],
  },
  {
    customer: 'Lucas Rodríguez',
    status: 'CANCELLED',
    paymentMethod: 'Tarjeta de Crédito',
    notes: 'Pedido cancelado\nPor: Administrador',
    items: [
      { product: 'ASUS ROG Strix G16', quantity: 1 },
      { product: 'Logitech MX Keys S', quantity: 1 },
    ],
  },
  {
    customer: 'Valentina Fernández',
    status: 'COMPLETED',
    paymentMethod: 'Tarjeta de Débito',
    notes: 'Pedido completado\nPor: Administrador',
    items: [
      { product: 'LG UltraGear 27" 144Hz', quantity: 1 },
      { product: 'Keychron K8 Pro', quantity: 1 },
      { product: 'Razer DeathAdder V3', quantity: 1 },
    ],
  },
  {
    customer: 'Diego González',
    status: 'SHIPPED',
    paymentMethod: 'Tarjeta de Crédito',
    trackingCode: '1234567890',
    notes: 'Pedido enviado con tracking: 1234567890\nPor: Administrador',
    items: [
      { product: 'AMD Ryzen 9 7950X', quantity: 1 },
      { product: 'Kingston Fury Beast 16GB', quantity: 2 },
      { product: 'Samsung 990 Pro 2TB NVMe', quantity: 1 },
    ],
  },
  {
    customer: 'Sofía Torres',
    status: 'PENDING',
    paymentMethod: 'Tarjeta de Débito',
    items: [
      { product: 'iPad Pro M4', quantity: 1 },
      { product: 'Jabra Evolve2 85', quantity: 1 },
    ],
  },
  {
    customer: 'Juan Pérez',
    status: 'PREPARING',
    paymentMethod: 'Tarjeta de Crédito',
    notes: 'Pedido en preparación\nPor: Administrador',
    items: [{ product: 'Dell XPS 13 Plus', quantity: 1 }],
  },
  {
    customer: 'María García',
    status: 'CANCELLED',
    paymentMethod: 'Tarjeta de Débito',
    notes: 'Pedido cancelado por solicitud del cliente\nPor: Administrador',
    items: [
      { product: 'NVIDIA RTX 4070 Ti', quantity: 1 },
      { product: 'Seagate Barracuda 4TB', quantity: 2 },
    ],
  },
];
